# Generated by Django 4.2.1 on 2024-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
