# Generated by Django 4.2.1 on 2024-05-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_breakfast_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "STANDARD"),
                    (1, "DELUXE"),
                    (2, "EXECUTIVE"),
                    (3, "SUPERIOR"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
